steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${PROJECT_ID}/${_REPO_NAME}/demo-app:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${PROJECT_ID}/${_REPO_NAME}/demo-app:$COMMIT_SHA']
