steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REPO_NAME:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REPO_NAME:$COMMIT_SHA']
