steps:
# build the container image
- name: 'gcr.io/gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${PROJECT_ID}/us-central1-docker.pkg.dev/amit-testing-277517/gmas-testing/demo-app:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/gcr.io/cloud-builders/docker'
  args: ['push', '${PROJECT_ID}/us-central1-docker.pkg.dev/amit-testing-277517/gmas-testing/demo-app:$COMMIT_SHA']
