steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/demoapp:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/demoapp:$COMMIT_SHA']
# substitutions:
#     _LOCATION: us-central1 # default value
#     _REPO_NAME: dockerimage # default value
